#!/bin/bash

DATE_STAMP="$(date +%Y%m%d)"
additional_tags=("${SOURCE_COMMIT}", "${DATE_STAMP}-${SOURCE_COMMIT}")

for tag in "${additional_tags[@]}"; do
    target="${DOCKER_REPO}:${tag}"
    docker tag ${IMAGE_NAME} ${target}
    docker push ${target}
done
